### ISSUE TITLE
Error when focus to element inside shadow DOM

### ISSUE THREAD

**Issue by trungtin** [theKashey/focus-lock#11]
The error is here:
```
Failed to execute 'getComputedStyle' on 'Window'
```

reference: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/host
will take a look to create MR later. Help is welcome :D 💃

**Comment by theKashey** [comment]
Not sure what is the real issue and how to reproduce it.

**Comment by trungtin** [comment]
here is the reproduce https://codesandbox.io/s/dawn-glitter-n5of7?fontsize=14

**Comment by theKashey** [comment]
When going up and checking all parents one should check for the ShadowRoot
```
node instanceof ShadowRoot ? node.host : node.parentNode
```

**Comment by emplums** [comment]
I'm dealing with this issue as well, though I'm not using the shadow DOM in my application. I'm getting these errors on the document nodes. I noticed that the conditional `node === document` here doesn't actually resolve to `true` even though it is the document node: https://github.com/theKashey/focus-lock/blob/master/src/utils/DOMutils.js#L16

![image](https://user-images.githubusercontent.com/8960591/64740717-219dda00-d4ab-11e9-85fc-27233164e9db.png)

Maybe a `node.nodeType === 9` would work here? https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType

**Comment by theKashey** [comment]
The problem is with two different documents, and that’s something focus-lock has no powers upon.
However, then more intelligent patch for document detection, or just wrapping check in try/catch should be enough to fix the problem.

**Comment by shabailiu** [comment]
I'm getting the same issue when using `react-focus-on` in an iframe. This is only an issue if there is a focus-able element (like a button) as a child of `FocusOn`. Here is a demo: https://codesandbox.io/embed/interesting-northcutt-t9whq

**Comment by theKashey** [comment]
Updates has been published to all packages. Not sure if does it solve ShadowDOM issue, but `document` is now detected via `nodeType` property

**Comment by shabailiu** [comment]
That was fast! Appreciate the fix, iframe detection works :)
