### ISSUE TITLE
Should readonly textareas be focusable?

### ISSUE THREAD

**Issue by jonbri** [theKashey/focus-lock#18]
Textareas having the `readonly` attribute are focusable by default, in other words, you can tab to them: https://codepen.io/jonbri/pen/rNxgKpE

However, it looks like readonly textareas are explicitly excluded in `src/utils/tabbables.js` on line 4: `'textarea:enabled:not([readonly])'`

Is there a reason why this exclusion was added? I couldn't glean any information from the Git history.

I'm coming at this from [react-focus-lock](https://github.com/theKashey/react-focus-lock)...is there an elegant way to have these textareas included in the `FocusLock` support? Perhaps I just need to add a `tabindex=0` to the textarea?

Here's a change I made in a fork to remove the exclusion, not sure if this is something that could turn into a pull-request:
https://github.com/jonbri/focus-lock/commit/f5c192d0da013a85cd8afa2b0a9b3c2bd2306a55#diff-91e5c4bfab3aec60dbd426f1cf881975

**Comment by theKashey** [comment]
The rule exists as a copy-paste of rules above. Once you point of it - I could fix it in no time.
Sounds like not all rules are correct, and I have add E2E test to double check how focus works in "real".

**Comment by theKashey** [comment]
Look like all `readonly` elements could be focused :)
