### ISSUE TITLE
Firefox on MacOS

### ISSUE THREAD

**Issue by andrey-hohlov** [theKashey/focus-lock#21]
It sounds like madness, but Firefox (checked on 82.0.3) on macOS (checked on 10.15.4) doesn't allow tab navigation on the links!
We found it when test how ```focus-lock``` helps to keep focus inside the dropdown menu.

At the same time, it works on Firefox on Windows 10.

More details: https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox

I set the checkbox

```
Use keyboard navigation to move focus between controls
```

 in the ```System Preferences - Keyboard -Shortcuts``` and now it works well.

This problem is not directly related to the ```focus-lock```. But let it be there for the next guy who will be close to spending a lot of time to understand why it doesn't work.

**Comment by theKashey** [comment]
It's more about Chrome not working according to OSX standards than Safari/FF working strangely. 
They actually doing everything as expected.

> Yep, it's not about FireFox only
