### ISSUE TITLE
Fails inside of WebComponents/shadowDOM

### ISSUE THREAD

**Issue by pearofducks** [theKashey/focus-lock#27]
Throws this error when it is walking up the DOM and bumps into the shadow root:

Error: `Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

---

Reproduction: https://github.com/pearofducks/focus-lock-reproduction

Run repro by doing:

- `yarn`
- `yarn dev`
-  `localhost:3000`
-  click on one of the elements inside the web component

**Comment by pearofducks** [comment]
Probably related: https://github.com/focus-trap/tabbable/pull/35/files

**Comment by theKashey** [comment]
Released in 0.9.2
Unfortunately, jsdom environment is not very compatible with web components and I was unable to create an automated test.
