### ISSUE TITLE
Uncaught TypeError: scope.contains is not a function

### ISSUE THREAD

**Issue by shaun-sweet** [theKashey/focus-lock#36]
Hello!  My company currently uses `react-focus-lock` as part of our SaaS app.  We updated that from `2.8.1` to `2.9.0` which also bumped the downstream `focus-lock` 

After this I seem to be seeing this error when hitting that code path.  

```
Uncaught TypeError: scope.contains is not a function
    at contains (DOMutils.js:47:1)
    at DOMutils.js:47:1
    at Array.some (<anonymous>)
    at contains (DOMutils.js:47:1)
    at DOMutils.js:47:1
    at Array.some (<anonymous>)
    at contains (DOMutils.js:47:1)
    at DOMutils.js:47:1
    at Array.some (<anonymous>)
    at contains (DOMutils.js:47:1)
```

It seems that if you have a form field named `contains` it breaks due to a conflict.

I've tracked it down to this particular line of code - https://github.com/theKashey/focus-lock/blob/699fe4a4ed53e714827b24a7623b45a72e2a0bd5/src/utils/DOMutils.ts#L48-L54
 
It is possible this is an upstream issue with how they are leveraging your code, but I figured i'd start here.  Here is a repro-repo as well! https://github.com/shaun-sweet/focus-lock-repro

Just pull it down and follow the readme instructions

**Comment by theKashey** [comment]
:woah: that was a little unexpected finding. A real foot gun.

**Comment by theKashey** [comment]
I was able to fix the problem. Unfortunately I was not able to reproduce the problem in jsdom environment, so this functionality is going to be still untested.

**Comment by shaun-sweet** [comment]
thank you :)
