### ISSUE TITLE
Disable focus instead of locking it inside

### ISSUE THREAD

**Issue by benjaminrobinet** [theKashey/focus-lock#39]
Hello ! I have an "offscreen" menu where I want to disable focus for it while it's "closed" (not display none). And lock the focus in it when it's opened. 
So is there a way to de the reverse of the main goal of focus lock ? I mean allow normal focusing loop but excluding a tree ?

Thanks !

**Comment by theKashey** [comment]
similar to https://github.com/theKashey/react-focus-lock/issues/133

So actually "this", lets call it _focus-holes_,  can be implemented, but there is still an open question about hiding stuff for screen readers as long as they should not _see_ hidden content as well.

And here is the expected solution - mark "hidden"(not display none) content as `aria-hidden` and ensure focus-lock "jumps over it" as expected.

Let me write a test for it and see how it works. Probably it's not (yet)
