### ISSUE TITLE
Blocked a frame from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by 7alip** [theKashey/focus-lock#49]
The error occurs in my Sentry logs. I don't have the library in my dependencies but I noticed from yarn.lock that it's being used in some ChakraUI components.

`Blocked a frame with origin `<domain>` from accessing a cross-origin frame.`

```bash
getActiveElement_getActiveElement @ ../../node_modules/focus-lock/dist/es2015/utils/getActiveElement.js:13
focusInside @ ../../node_modules/focus-lock/dist/es2015/focusInside.js:14
activateTrap @ ../../node_modules/react-focus-lock/dist/es2015/Trap.js:115
(anonymous function) @ app:///_next/static/chunks/970-47e49bfbec398534.js:1
d @ app:///_next/static/chunks/970-47e49bfbec398534.js:1
p @ app:///_next/static/chunks/970-47e49bfbec398534.js:1
sentryWrapped @ ../../node_modules/@sentry/browser/esm/helpers.js:90
```

**Comment by 7alip** [comment]
@theKashey This is the AI solution generated by Sentry

___

### Problem Description

Looks like we have a SecurityError on our hands! The app is trying to access a cross-origin frame from "[https://..."](https://...%22/) and it's being blocked. The stack trace shows that the error happened in the `getActiveElement` function in the `focus-lock` library. Specifically, it's trying to get the active element from a `HTMLIFrameElement` and it's not being allowed.

### Proposed Solution

Unfortunately, Sentry can't fix this for us, but we can still work on a solution! To fix this issue, we need to make sure that we're not trying to access a cross-origin frame. One solution is to check if the HTMLIFrameElement is from the same origin as the app before trying to access it.

Here's an example of what the fixed code could look like:

```ts
if (activeElement instanceof HTMLIFrameElement &&
    activeElement.contentWindow.location.origin !== window.location.origin) {
  return undefined;
}
```

We would place this code in the getActiveElement function, right before the line where it tries to access the contentWindow.document.

**Comment by theKashey** [comment]
:mindblow: Everybody introduces AI nowadays!

The "fix" was introduced at https://github.com/theKashey/focus-lock/commit/860e2831#diff-913aa6f7e63ffc5c8bb2704d4762c851c00657c5ed67693117e0ce5b118a2373R16, look like some things cannot be contained within simple try catch, even if they should
