### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'tagName') if no innerTabbable elements present

### ISSUE THREAD

**Issue by veksa** [theKashey/focus-lock#63]
Error in focusSolver function if there are no any orderedInnerElements with tabIndex >= 0

![image](https://github.com/theKashey/focus-lock/assets/6467881/77d459e2-d332-42a4-b8c0-8d10aaeb5a65)

**Comment by theKashey** [comment]
This probably explains #53

Behaviour has changed at 1.0.1 as a part of focus restoration correction, where non-tabbale elements were not considered as possible options. 
Use case with no tabble elements was missed, sorry

**Comment by theKashey** [comment]
Fix released in 1.3.1
