### ISSUE TITLE
captureFocusRestore unexpectedly picks other node when captured element still present

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [theKashey/focus-lock#65]
With a DOM structure like this, `captureFocusRestore` of b1 will unexpectedly pick b2 on restore:

```html
<div><button id="b1"></button><button id="b2"></button></div>
````

I've added [this and a related case here](https://github.com/theKashey/focus-lock/compare/master...microbit-matt-hillsdon:focus-lock:return-focus-bug?expand=1) so you can see the failure.

I think using `current` rather than `left?.nextElementSibling` has to be part of the fix (as there is no left) but to keep other tests passing a bigger change is needed.

I came to this via [Chakra UI](https://chakra-ui.com/) (which uses react-focus-lock) when trying to upgrade Chakra UI in my project. Recently installed Chakra UI will focus unexpected (next sibling) buttons after showing modals as they pass `returnFocus=true` to react-focus-lock which, in recent versions, uses the new logic to restore focus. I suspect this will affect other clients of react-focus-lock too. I'm working around it by using react-focus-lock 2.10.1.

**Comment by theKashey** [comment]
Let me add your tests to the suite and make them pass

🙇 for the so ease to reproduce issue

**Comment by theKashey** [comment]
v1.3.4 with the fix just released

**Comment by microbit-matt-hillsdon** [comment]
Thanks for the quick fix - all working well for me.
