### ISSUE TITLE
WeakRef is not defined in Safari < 14

### ISSUE THREAD

**Issue by veksa** [theKashey/focus-lock#68]
WeakRef is not defined in Safari < 14.1

![image](https://github.com/theKashey/focus-lock/assets/6467881/1a7d101f-f3d7-43f7-b650-d1d359739985)

![image](https://github.com/theKashey/focus-lock/assets/6467881/f72cb1a0-03df-4537-8bf8-82fad056bc30)

**Comment by theKashey** [comment]
v1.3.5 should fix your problem
