### ISSUE TITLE
elements with contenteditable seem to behave as though they have a larger tabIndex 

### ISSUE THREAD

**Issue by alex-e-leon** [theKashey/focus-lock#71]
When running autofocus on a collection of focusable items - contenteditable items seem to take priority over other items, unless you manually set the tabindex on it to 0.

I've only tested in chrome, so I'm not sure if this behaviour is reproducible in other browsers.

I think the default behaviour should be that contenteditable items have the same priority as other focusable items?

**Comment by theKashey** [comment]
Content editable has a little _fucked_ tabIndex (#55) and was not focusable at all. Sounds like now it's on the side.

Thanks for reporting the problem 👍

**Comment by alex-e-leon** [comment]
Yeah, I figured this was a browser issue - not sure whether it's worth fighting the browser on this one or not, but 2 options I can think of:
- Manually override the default browser behaviours/ordering and implement a custom tab ordering. Pros, would behave as expected. Cons, overrides browser default tab behaviour, may need to look through all tabbable elements to get the ordering correct.
- Document the behaviour in the README somewhere. If I'd seen this in the README it would have saved me half an hour before I manually set a tabindex of 0 on mine.

**Comment by alex-e-leon** [comment]
Seperately, while working through this, I also noticed that focus-lock seems to prioritize autofocus on items with tabindex -1, however a tabindex of -1 is supposed to mean as far as I'm aware that the item should not be tabbable with the keyboard, so I would expect autofocus to skip these items.

Not sure what your thoughts are on this @theKashey (or if this should just be a seperate issue) but thought I'd share as well. In my case I've worked around this issue by setting `data-no-autofocus`, but it was another place where the out of the box behaviour caught me by surprise
